### ISSUE TITLE
user-can-view-all-art.md

### ISSUE THREAD

**Issue by sinadaryaei** [sinadaryaei/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view random art from the gallery and use the random button to continue seeing more random art.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

API will load images from the museum onto the placeholder images.

## 🖼️ Wireframes

> ##### ![image](https://user-images.githubusercontent.com/125223265/235202433-f76bb7ed-f619-4452-b046-83e0ef114692.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] 
- [ ] ...
- [ ] ...
- [ ] ...

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
